#-------------------------------
# General Site Settings

title: Portfolio de Sylvain

menu:
- {name: 'Portfolio', url: ''}
#- {name: 'Blog',     url: 'blog'}
- {name: 'À Propros',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Technicien ERP VIF chez Viandes de Bresse',   url: 'vif'}
- {name: 'BTS SIO SISR',   url: 'sio'}
- {name: 'Kotlin Android',  url: 'kotlin'}
- {name: 'Traversée du Desert',  url: 'desert'}
- {name: 'Classes Préparatoires aux Grandes Écoles', url: 'cpge'}
#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/lenpaul'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/lenpaul'}
- {icon: 'envelope',  link: 'mailto:mailto:l.nguyen.paul@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
